CREATE TABLE IF NOT EXISTS heroes(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    class VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS powers(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    hero_id INTEGER NOT NULL
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_POWERS_HEROES FOREIGN KEY (hero_id) 
    REFERENCES heroes(id)
    ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS items(
    id SERIAL PRIMARY KEY,
    rarity VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    hero_id INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_ITEMS_HERO FOREIGN KEY (hero_id)
    REFERENCES heroes(id)
    ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS hero_items(
    hero_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    PRIMARY KEY (hero_id, item_id),
    CONSTRAINT fk_hero_items_hero FOREIGN KEY (hero_id) 
        REFERENCES heroes(id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_hero_items_item FOREIGN KEY (item_id) 
        REFERENCES items(id) 
        ON DELETE CASCADE
)